In [103]:
#Gaberial Campese
#DATS6202 Machine Learning I
#Assignment #4

In [104]:
#Importing libraries
from sklearn.model_selection import train_test_split
import pandas as pd #import pandas
import matplotlib.pyplot as plt
import numpy as np #import numpy
from sklearn import preprocessing

In [105]:
#1. Use and analyze load_digits dataset
from sklearn.datasets import load_digits #load digits dataset

In [106]:
digits = load_digits() #initialize digits

In [107]:
#Begin brief analysis
digits.data.shape #1797 rows, 64 columns

(1797, 64)

In [108]:
digits.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [109]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [110]:
digits.DESCR

"Optical Recognition of Handwritten Digits Data Set\n===================================================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttp://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixels are counted 

In [111]:
import statistics
statistics.stdev(digits.target) #standard deviation on target

2.8284271247461903

In [112]:
statistics.mean(digits.target) #mean

4

In [113]:
#2. Normalize the data set by MinMaxScaler
MinMaxScaler = preprocessing.MinMaxScaler() #load MinMax Scaler

In [114]:
digits.data = MinMaxScaler.fit_transform(digits.data) #using MinMaxScaler on dataset

In [115]:
digits.data #We see MinMaxScaler working... all values between 0-1

array([[ 0.    ,  0.    ,  0.3125, ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.625 ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  1.    ,  0.5625,  0.    ],
       ..., 
       [ 0.    ,  0.    ,  0.0625, ...,  0.375 ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.125 , ...,  0.75  ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.625 , ...,  0.75  ,  0.0625,  0.    ]])

In [116]:
X, y = np.array(digits.data), digits.target #initialize X, y

In [117]:
#split into test/train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [118]:
X_train.shape #good to check

(1437, 64)

In [119]:
X

array([[ 0.    ,  0.    ,  0.3125, ...,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.625 ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  1.    ,  0.5625,  0.    ],
       ..., 
       [ 0.    ,  0.    ,  0.0625, ...,  0.375 ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.125 , ...,  0.75  ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.625 , ...,  0.75  ,  0.0625,  0.    ]])

In [120]:
#3. Train following classifiers on the dataset
#a. kNN
#b. Naïve Bayes
#c. Random Forest

#4. For each classifier show:
#a. training score
#b. test score

In [121]:
#kNN Classifier
from sklearn.neighbors import KNeighborsClassifier #import kNN Classifier
kNNClassifier = KNeighborsClassifier()
kNNClassifier.fit(X_train, y_train) #train kNN on dataset

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [122]:
#kNN Training & Test Scores
print("Training score: {:.3f}".format(kNNClassifier.score(X_train, y_train))) #kNN train score
print("Test score: {:.3f}".format(kNNClassifier.score(X_test, y_test))) #kNN test score

Training score: 0.990
Test score: 0.986


In [123]:
#Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB #import Naive Bayes
nbClassifier = GaussianNB()
nbClassifier.fit(X_train, y_train) #train Naive Bayes on dataset

GaussianNB(priors=None)

In [124]:
#Naive Bayes Training & Test Scores
print("Training score: {:.3f}".format(nbClassifier.score(X_train, y_train))) #Naive Bayes train score
print("Test score: {:.3f}".format(nbClassifier.score(X_test, y_test))) #Naive Bayes test score

Training score: 0.830
Test score: 0.833


In [125]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier #import RandomForestClassifier
rfClassifier = RandomForestClassifier(n_estimators=100)
rfClassifier.fit(X_train, y_train) #train Random Forest Classifier on dataset

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [126]:
#Random Forest Training & Test Scores
print("Training score: {:.3f}".format(rfClassifier.score(X_train, y_train))) #Random Forest train score
print("Test score: {:.3f}".format(rfClassifier.score(X_test, y_test))) #Random Forest test score
#All of the scores were rounded to 3 decimal places

Training score: 1.000
Test score: 0.978


In [127]:
#5. Devise a majority voting classifier, you may use VotingClassifier in sklearn.ensemble package

#Majority Voting Classifier
from sklearn.ensemble import VotingClassifier #import VotingClassifier
mvClassifier = VotingClassifier(estimators= [('kNN', kNNClassifier), ('nb', nbClassifier), ('rf', rfClassifier)], 
                                            voting='hard') #building Majority Voting Classifier
mvClassifier.fit(X_train, y_train) #training classifier on dataset

VotingClassifier(estimators=[('kNN', KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')), ('nb', GaussianNB(priors=None)), ('rf', RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini'...n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [128]:
#Majority Voting Classifier Train/Test Scores
print("Training score: {:.3f}".format(mvClassifier.score(X_train, y_train))) #Voting train score
print("Test score: {:.3f}".format(mvClassifier.score(X_test, y_test))) #Voting test score

Training score: 0.991
Test score: 0.983
